# Generated by Django 6.0.3 on 2026-03-14 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['slug'], name='blog_catego_slug_fc0bb9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('content', models.TextField()),
                ('summary', models.CharField(blank=True, max_length=200)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='posts/%Y/%m/')),
                ('seo_description', models.CharField(blank=True, max_length=200)),
                ('seo_keywords', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('drafts', 'Drafts'), ('published', 'Published'), ('archived', 'Archived')], default='drafts', max_length=200)),
                ('commentaries_permission', models.BooleanField(default=True)),
                ('count_views', models.PositiveIntegerField(default=0)),
                ('count_commentaries', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.category')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['slug'], name='blog_post_slug_cdb902_idx'), models.Index(fields=['status', '-published_at'], name='blog_post_status_615533_idx'), models.Index(fields=['author'], name='blog_post_author__038a48_idx'), models.Index(fields=['category'], name='blog_post_categor_82832f_idx'), models.Index(fields=['-count_views'], name='blog_post_count_v_ecf7fe_idx')],
            },
        ),
    ]
