# Generated by Django 6.0.3 on 2026-03-28 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_updated_at_category_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='archived_by_role',
            field=models.CharField(blank=True, choices=[('user', 'User'), ('mod', 'Moderator'), ('admin', 'Administrator')], default='', max_length=20),
        ),
    ]
