# Generated by Django 6.0.3 on 2026-03-13 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rol', models.CharField(choices=[('user', 'User'), ('mod', 'Moderator'), ('admin', 'Administrador')], default='user', help_text='Rol del usuario. Admin solo puede ser asignado por superuser', max_length=20)),
                ('bio', models.TextField(blank=True, help_text='Biografía del usuario (máximo 500 caracteres)', max_length=500, null=True)),
                ('profile_picture', models.ImageField(blank=True, default='profiles/default_avatar.png', help_text='Foto de perfil (JPEG, PNG, máximo 5MB)', null=True, upload_to='profiles/%Y/%m/')),
                ('is_moderator', models.BooleanField(default=False, help_text='Indica si el usuario puede moderar contenido')),
                ('has_email_confirmated', models.BooleanField(default=False, help_text='Email ha sido confirmado por el usuario')),
                ('subscribe_notifications', models.BooleanField(default=True, help_text='Recibir notificaciones por email')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del perfil')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='Última fecha de actualización')),
                ('date_last_access', models.DateTimeField(blank=True, help_text='Último acceso al sitio', null=True)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['rol'], name='users_profi_rol_26cf09_idx'), models.Index(fields=['user'], name='users_profi_user_id_7297d9_idx')],
            },
        ),
    ]
