# Generated by Django 6.0.3 on 2026-03-14 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='rol',
            field=models.CharField(choices=[('user', 'User'), ('mod', 'Moderator'), ('admin', 'Administrator')], default='user', help_text='Rol del usuario. Admin solo puede ser asignado por superuser', max_length=20),
        ),
    ]
