# Generated by Django 6.0.3 on 2026-03-16 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profileuser_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Última fecha de actualización'),
        ),
    ]
