# Generated by Django 6.0.3 on 2026-03-21 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profileuser_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Foto de perfil (JPEG, PNG, máximo 5MB)', null=True, upload_to='profiles/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Última fecha de actualización'),
        ),
    ]
