# Generated by Django 6.0.3 on 2026-03-22 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profileuser_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Última fecha de actualización'),
        ),
    ]
