"""
Django settings for config project.
Generated by 'django-admin startproject' using Django 6.0.3.

Versión corregida para deploy en Render (app) + Neon (base de datos PostgreSQL).
Los comentarios marcados con "FIX:" explican qué se cambió respecto a tu versión original y por qué.
"""

from pathlib import Path
from decouple import config, Csv
import dj_database_url
from django.utils.csp import CSP  # FIX: necesario para el nuevo sistema de CSP de Django 6.0

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# ---------------------------------------------------------------------------
# Seguridad básica
# ---------------------------------------------------------------------------

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

# Lista de dominios que pueden "servir" tu Django (protege contra ataques de Host header).
# En Render, agrega tu-app.onrender.com como variable de entorno ALLOWED_HOSTS.
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())


# ---------------------------------------------------------------------------
# Application definition
# ---------------------------------------------------------------------------

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',

    # FIX: cloudinary_storage debe ir ANTES que staticfiles para poder interceptar
    # cómo se guardan los archivos subidos por los usuarios.
    'cloudinary_storage',
    'django.contrib.staticfiles',
    'cloudinary',
    'rest_framework',
    'django_filters',
    'crispy_forms',
    'crispy_bootstrap5',
    'drf_spectacular',          # Para Swagger
    'corsheaders',              # Para evitar conflicto de puertos con el frontend

    # Local apps
    'apps.users.apps.UsersConfig',
    'apps.blog',
    'apps.api',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.csp.ContentSecurityPolicyMiddleware',  # FIX: activa de verdad la política CSP de abajo
    'whitenoise.middleware.WhiteNoiseMiddleware',              # Sirve los archivos estáticos sin servidor aparte
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'  # Se usa config porque es la carpeta contenedora

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# ---------------------------------------------------------------------------
# Database — usa Neon si existe DATABASE_URL (Render), si no, tus variables locales
# ---------------------------------------------------------------------------

DATABASE_URL = config('DATABASE_URL', default=None)

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,          # FIX: reutiliza conexiones 10 min en vez de abrir una por request
            conn_health_checks=True,   # FIX: evita errores cuando Neon "duerme" la base por inactividad
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': config('DB_ENGINE', default='django.db.backends.postgresql'),
            'NAME': config('DB_NAME'),
            'USER': config('DB_USER'),
            'PASSWORD': config('DB_PASSWORD'),
            'HOST': config('DB_HOST', default='localhost'),
            'PORT': config('DB_PORT', default='5432'),
        }
    }

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ---------------------------------------------------------------------------
# Internationalization
# ---------------------------------------------------------------------------

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# ---------------------------------------------------------------------------
# Static & media files
# ---------------------------------------------------------------------------

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'config' / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

# FIX: STATICFILES_STORAGE fue eliminado en Django 6.0 (estaba obsoleto desde 4.2).
# El reemplazo oficial es el diccionario STORAGES, con una entrada para archivos
# subidos ("default") y otra para estáticos ("staticfiles").
STORAGES = {
    "default": {
        # FIX: en DEBUG usamos el disco local (más simple para programar);
        # en producción usamos Cloudinary, porque el disco de Render es temporal
        # y perdería las imágenes que suban los usuarios.
        "BACKEND": (
            "django.core.files.storage.FileSystemStorage" if DEBUG
            else "cloudinary_storage.storage.MediaCloudinaryStorage"
        ),
    },
    "staticfiles": {
        "BACKEND": (
            "whitenoise.storage.CompressedStaticFilesStorage" if DEBUG
            else "whitenoise.storage.CompressedManifestStaticFilesStorage"
        ),
    },
}

# Credenciales de Cloudinary — se leen de variables de entorno, nunca escritas en el código.
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': config('CLOUDINARY_CLOUD_NAME', default=''),
    'API_KEY': config('CLOUDINARY_API_KEY', default=''),
    'API_SECRET': config('CLOUDINARY_API_SECRET', default=''),
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'config' / 'media'  # Solo se usa en local (DEBUG=True)


# ---------------------------------------------------------------------------
# REST Framework
# ---------------------------------------------------------------------------

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}


# ---------------------------------------------------------------------------
# CORS
# ---------------------------------------------------------------------------

# FIX: antes, CORS_ALLOW_ALL_ORIGINS=True anulaba por completo la lista de abajo.
# Aquí solo se permite "todo" en desarrollo; en producción se respeta la lista,
# que debes llenar con la URL real de tu frontend vía variable de entorno.
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOWED_ORIGINS = config('CORS_ALLOWED_ORIGINS', default='', cast=Csv())


# ---------------------------------------------------------------------------
# Crispy Forms
# ---------------------------------------------------------------------------

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"


# ---------------------------------------------------------------------------
# Login
# ---------------------------------------------------------------------------

LOGIN_URL = 'users:login'
LOGIN_REDIRECT_URL = 'blog:index'
LOGOUT_REDIRECT_URL = 'blog:index'


# ---------------------------------------------------------------------------
# Security (production only)
# ---------------------------------------------------------------------------

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # FIX: el nombre correcto en Django 6.0 es SECURE_CSP (no SECURE_CONTENT_SECURITY_POLICY).
    # Sin el nombre correcto Y el middleware de arriba, esto no hacía nada antes.
    SECURE_CSP = {
        "default-src": [CSP.SELF],
        "script-src": [CSP.SELF, CSP.UNSAFE_INLINE],
        "style-src": [CSP.SELF, CSP.UNSAFE_INLINE],
    }
    # Nota: quité SECURE_BROWSER_XSS_FILTER porque Django ya lo eliminó
    # (los navegadores modernos ignoran esa cabecera hace años).


# ---------------------------------------------------------------------------
# Email
# ---------------------------------------------------------------------------

if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
# Recuerda: esto debe ser una "Contraseña de aplicación" de Google, no tu password normal
# (Gmail bloquea el login por SMTP con la contraseña de la cuenta).
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('EMAIL_HOST_USER', default='')